"""
the host-side LUT generator.
emits .fj data tables (lookup tables) from python value lists - the fixed-point design
replaces runtime divides/trig with integer-indexed lookups (a hex.div is ~68K ops; a
table lookup is ~O(w) ops via hex.read_table).

the emitted layout is consecutive `hex.vec entry_nibbles, value` entries: entry k sits at
`label + k * entry_nibbles * dw`, exactly the layout `hex.read_table` indexes at runtime.
"""

import math
from typing import List, Sequence

__all__ = [
    'encode_fixed_point',
    'generate_byte_lut_fj',
    'generate_lut_fj',
    'generate_reciprocal_lut_fj',
    'generate_sine_lut_fj',
]


def encode_fixed_point(value: float, fraction_bits: int, total_bits: int) -> int:
    """
    encode a real value as a two's-complement fixed-point word (e.g. 16.16: fraction_bits=16,
    total_bits=32). rounds to nearest.
    @return: the raw unsigned word (negative values are two's-complement encoded)
    @raise ValueError: if the value doesn't fit the format
    """
    scaled = round(value * (1 << fraction_bits))
    signed_min, signed_max = -(1 << (total_bits - 1)), (1 << (total_bits - 1)) - 1
    if not signed_min <= scaled <= signed_max:
        raise ValueError(
            f'value {value} (scaled {scaled}) does not fit a signed {total_bits}-bit'
            f' fixed-point word with {fraction_bits} fraction bits'
        )
    return scaled & ((1 << total_bits) - 1)


def generate_lut_fj(label: str, values: Sequence[int], entry_nibbles: int) -> str:
    """
    emit a .fj data table: `label:` followed by one `hex.vec entry_nibbles, value` per entry.
    entry k of the table sits at `label + k * {entry_nibbles} * dw` - indexable at runtime
    with `hex.read_table {entry_nibbles}, dst, label, idx_n, idx`.
    @param values: the raw (already-encoded) unsigned entry words
    @raise ValueError: if any value is negative or doesn't fit entry_nibbles
    """
    max_value = (1 << (4 * entry_nibbles)) - 1
    lines: List[str] = [
        f'// LUT "{label}": {len(values)} entries of {entry_nibbles} nibbles' f' (generated by flipjump.lut_generator)',
        f'{label}:',
    ]
    for index, value in enumerate(values):
        if not 0 <= value <= max_value:
            raise ValueError(
                f'{label}[{index}] = {value} does not fit {entry_nibbles} nibbles'
                f' (encode negative values with encode_fixed_point first)'
            )
        lines.append(f'    hex.vec {entry_nibbles}, {hex(value)}')
    return '\n'.join(lines) + '\n'


def generate_reciprocal_lut_fj(label: str, count: int, fraction_bits: int, entry_nibbles: int) -> str:
    """
    emit a reciprocal table: entry i is round(2^fraction_bits / i), entry 0 is clamped to the
    max entry value. replaces runtime division by an integer-indexed lookup.
    """
    max_value = (1 << (4 * entry_nibbles)) - 1
    values = ([max_value] + [min(round((1 << fraction_bits) / i), max_value) for i in range(1, count)])[:count]
    return generate_lut_fj(label, values, entry_nibbles)


def generate_sine_lut_fj(label: str, count: int, fraction_bits: int, entry_nibbles: int) -> str:
    """
    emit a sine table: entry k is sin(2*pi*k/count) as a signed fixed-point word of
    4*entry_nibbles bits (two's-complement encoded).
    """
    values = [
        encode_fixed_point(math.sin(2 * math.pi * k / count), fraction_bits, 4 * entry_nibbles) for k in range(count)
    ]
    return generate_lut_fj(label, values, entry_nibbles)


def generate_byte_lut_fj(label: str, values: Sequence[int]) -> str:
    """
    emit a .fj packed-byte data table: `label:` followed by one `;value * dw` op per entry
    (the byte lives in the op's data bits). entry k sits at `label + k * dw` - indexable at
    runtime with `hex.read_table_byte dst, label, idx_n, idx`. 2x smaller than a
    generate_lut_fj table of hex[:2] entries - right for colormaps and light-level tables.
    @param values: the entry bytes (0..255)
    @raise ValueError: if any value is not a byte
    """
    lines: List[str] = [
        f'// byte LUT "{label}": {len(values)} packed-byte entries' f' (generated by flipjump.lut_generator)',
        f'{label}:',
    ]
    for index, value in enumerate(values):
        if not 0 <= value <= 0xFF:
            raise ValueError(f'{label}[{index}] = {value} is not a byte (0..255)')
        lines.append(f'    ;{hex(value)} * dw')
    return '\n'.join(lines) + '\n'
